### ISSUE TITLE
stickers/freifunk_ortenau_logo_hotspot.svg is not "ortenau"

### ISSUE THREAD

**Issue by Tanarri** [ffortenau/werbematerial#1]
Hi,
the file is named "...ortenau..." but the content ist "...karlsruhe..."

a) Please rename the file to stickers/freifunk_kalrsruhe_logo_hotspot.svg
b) and create a new file with the right content and filename "stickers/freifunk_ortenau_logo_hotspot.svg"

Greetings
Eugen

**Comment by jannispinter** [comment]
Sticker directory removed, sticker files can be found in "logos"
